# fly.toml app configuration file generated for youtube-clone-green-field-628 on 2025-03-18T11:29:53+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'youtube-clone-green-field-628'
primary_region = 'sin'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
